/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const WebcheckWaiverIndexLazyRouteImport =
  createFileRoute('/webcheck-waiver/')()
const WaiverNoticeIndexLazyRouteImport = createFileRoute('/waiver-notice/')()
const UiKitIndexLazyRouteImport = createFileRoute('/ui-kit/')()
const NextKinProspectiveWardIndexLazyRouteImport = createFileRoute(
  '/next-kin-prospective-ward/',
)()
const ApplicantCredibilityApplicationIndexLazyRouteImport = createFileRoute(
  '/applicant-credibility-application/',
)()
const AdultGuardianshipIndexLazyRouteImport = createFileRoute(
  '/adult-guardianship/',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const WebcheckWaiverIndexLazyRoute = WebcheckWaiverIndexLazyRouteImport.update({
  id: '/webcheck-waiver/',
  path: '/webcheck-waiver/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/webcheck-waiver/index.lazy').then((d) => d.Route),
)
const WaiverNoticeIndexLazyRoute = WaiverNoticeIndexLazyRouteImport.update({
  id: '/waiver-notice/',
  path: '/waiver-notice/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/waiver-notice/index.lazy').then((d) => d.Route),
)
const UiKitIndexLazyRoute = UiKitIndexLazyRouteImport.update({
  id: '/ui-kit/',
  path: '/ui-kit/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ui-kit/index.lazy').then((d) => d.Route))
const NextKinProspectiveWardIndexLazyRoute =
  NextKinProspectiveWardIndexLazyRouteImport.update({
    id: '/next-kin-prospective-ward/',
    path: '/next-kin-prospective-ward/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/next-kin-prospective-ward/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ApplicantCredibilityApplicationIndexLazyRoute =
  ApplicantCredibilityApplicationIndexLazyRouteImport.update({
    id: '/applicant-credibility-application/',
    path: '/applicant-credibility-application/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/applicant-credibility-application/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdultGuardianshipIndexLazyRoute =
  AdultGuardianshipIndexLazyRouteImport.update({
    id: '/adult-guardianship/',
    path: '/adult-guardianship/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/adult-guardianship/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/adult-guardianship': typeof AdultGuardianshipIndexLazyRoute
  '/applicant-credibility-application': typeof ApplicantCredibilityApplicationIndexLazyRoute
  '/next-kin-prospective-ward': typeof NextKinProspectiveWardIndexLazyRoute
  '/ui-kit': typeof UiKitIndexLazyRoute
  '/waiver-notice': typeof WaiverNoticeIndexLazyRoute
  '/webcheck-waiver': typeof WebcheckWaiverIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/adult-guardianship': typeof AdultGuardianshipIndexLazyRoute
  '/applicant-credibility-application': typeof ApplicantCredibilityApplicationIndexLazyRoute
  '/next-kin-prospective-ward': typeof NextKinProspectiveWardIndexLazyRoute
  '/ui-kit': typeof UiKitIndexLazyRoute
  '/waiver-notice': typeof WaiverNoticeIndexLazyRoute
  '/webcheck-waiver': typeof WebcheckWaiverIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/adult-guardianship/': typeof AdultGuardianshipIndexLazyRoute
  '/applicant-credibility-application/': typeof ApplicantCredibilityApplicationIndexLazyRoute
  '/next-kin-prospective-ward/': typeof NextKinProspectiveWardIndexLazyRoute
  '/ui-kit/': typeof UiKitIndexLazyRoute
  '/waiver-notice/': typeof WaiverNoticeIndexLazyRoute
  '/webcheck-waiver/': typeof WebcheckWaiverIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adult-guardianship'
    | '/applicant-credibility-application'
    | '/next-kin-prospective-ward'
    | '/ui-kit'
    | '/waiver-notice'
    | '/webcheck-waiver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adult-guardianship'
    | '/applicant-credibility-application'
    | '/next-kin-prospective-ward'
    | '/ui-kit'
    | '/waiver-notice'
    | '/webcheck-waiver'
  id:
    | '__root__'
    | '/'
    | '/adult-guardianship/'
    | '/applicant-credibility-application/'
    | '/next-kin-prospective-ward/'
    | '/ui-kit/'
    | '/waiver-notice/'
    | '/webcheck-waiver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdultGuardianshipIndexLazyRoute: typeof AdultGuardianshipIndexLazyRoute
  ApplicantCredibilityApplicationIndexLazyRoute: typeof ApplicantCredibilityApplicationIndexLazyRoute
  NextKinProspectiveWardIndexLazyRoute: typeof NextKinProspectiveWardIndexLazyRoute
  UiKitIndexLazyRoute: typeof UiKitIndexLazyRoute
  WaiverNoticeIndexLazyRoute: typeof WaiverNoticeIndexLazyRoute
  WebcheckWaiverIndexLazyRoute: typeof WebcheckWaiverIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webcheck-waiver/': {
      id: '/webcheck-waiver/'
      path: '/webcheck-waiver'
      fullPath: '/webcheck-waiver'
      preLoaderRoute: typeof WebcheckWaiverIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver-notice/': {
      id: '/waiver-notice/'
      path: '/waiver-notice'
      fullPath: '/waiver-notice'
      preLoaderRoute: typeof WaiverNoticeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit/': {
      id: '/ui-kit/'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-kin-prospective-ward/': {
      id: '/next-kin-prospective-ward/'
      path: '/next-kin-prospective-ward'
      fullPath: '/next-kin-prospective-ward'
      preLoaderRoute: typeof NextKinProspectiveWardIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicant-credibility-application/': {
      id: '/applicant-credibility-application/'
      path: '/applicant-credibility-application'
      fullPath: '/applicant-credibility-application'
      preLoaderRoute: typeof ApplicantCredibilityApplicationIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-guardianship/': {
      id: '/adult-guardianship/'
      path: '/adult-guardianship'
      fullPath: '/adult-guardianship'
      preLoaderRoute: typeof AdultGuardianshipIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdultGuardianshipIndexLazyRoute: AdultGuardianshipIndexLazyRoute,
  ApplicantCredibilityApplicationIndexLazyRoute:
    ApplicantCredibilityApplicationIndexLazyRoute,
  NextKinProspectiveWardIndexLazyRoute: NextKinProspectiveWardIndexLazyRoute,
  UiKitIndexLazyRoute: UiKitIndexLazyRoute,
  WaiverNoticeIndexLazyRoute: WaiverNoticeIndexLazyRoute,
  WebcheckWaiverIndexLazyRoute: WebcheckWaiverIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
